name = "TrussCExample"
uuid = "f170db11-09bc-475a-afc5-9d1a5422eec2"
version = "0.2.3"
authors = ["Fumiya Funatsu <funatsu.fumiya@gmail.com>"]

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TrussC = "0a376bb9-dc76-480f-94ee-afa071fbfff1"
TrussC_prebuilt_jll = "cfe08a50-4fff-11f1-bfed-990c59676b1f"

[compat]
Printf = "1.11.0"
TrussC = "0.2.3"
TrussC_prebuilt_jll = "0.2.3"
